
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 150
  Exclude:
  - 'bin/*'

Metrics/BlockLength:
  Exclude:
  - 'bin/*'
  - 'db/schema.rb'
  - 'db/migrate/*'

Metrics/MethodLength:
  Exclude:
  - 'bin/*'
  - 'db/schema.rb'
  - 'db/migrate/*'

Metrics/CyclomaticComplexity:
  Exclude:
  - 'bin/*'

Metrics/PerceivedComplexity:
  Exclude:
  - 'bin/*'

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Max: 25
